#+title: 親精神性
#+author: haruki7049
#+email: tontonkirikiri@gmail.com
#+language: Japanese
#+STARTUP: overview
#+OPTIONS: \n:t

* 思想

#+begin_quote
  汝思考する時、世界は生まれる。\\
  汝思考する時、力が生まれる。\\

  汝より生まれし世界には、光もない。汝のみが光あれと述べられる。\\
  汝より生まれし世界には、法もない。汝のみが在り方を述べられる。\\
  汝より生まれし世界には、力はある。汝のみが使い道を述べられる。\\

  思考せよ。そこに汝のための世界はある。
#+end_quote

世界は人の思考によって生み出すことができる。生み出した世界には光も人もなく、ただエネルギーのみが存在する。その人の思考によってのみ、そのまるで無法地帯とも呼べる世界を耕せるのだ。

思考はエネルギーを生み出す。勿論そのエネルギーは外界には排出出来ないものだ。だがしかし、もしも思考のエネルギーを外界に排出出来るとしたら——

* COMMENT 親精神性

原作ガンダム世界と原作ジョジョ世界を混ぜた世界での、色々ないざこざを記した話。

** あらすじ

宇宙世紀ガンダムの宇宙が百巡くらいした＆ジョジョ六部以降のどこかの宇宙が百巡くらいした後の話。何巡もしていれば宇宙と宇宙が合わさることくらいあるでしょ（適当）。つまり、スタンドって概念も出てくるし、ニュータイプなんて概念も同時に出てくるということ。挙げ句の果てには波紋も出せるし柱の男も出せる。ガンダムもモビルスーツも。

** これの結末

- 戦いの末にこの世界を崩壊させる
  - 理由は、混ざり合った世界は不安定だから、それぞれの世界の住人同士で暴れられたり交流されると崩壊しやすくなる、ということにする
- 主人公の精神体を別世界に飛ばされる流れを結末に置く
  - なぜ？
  - 崩壊していく世界にそのままいると自意識から外界を観測できなくなる、つまり死の状態になるため、それを避けさせるために仲間のスタンド使いがそれを祈ったから

** 作ろうと思った理由

なんでこの概念たちを合わせようかと思ったかは、以下の感じで近しいものを感じたから。
| 第一段階     | 第二段階     | 第三段階         |
|--------------+--------------+------------------|
| スタンド     |              | 精神エネルギー   |
| ニュータイプ | 精神の感応波 | 精神エネルギー？ |

** 世界観の詳細

この世界でのスタンド使いは百巡後の世界にいるものだから、黄金の精神は消え去っている。五部のミスタとかの生存能力とかを顧みて、強くイメージができればなんでもできるという設定。腕が切り離されたとしても、スタンドエネルギーを使い果たせばくっつけられるなど。印象としては二部の柱の男の感じが近い。おそらく荒木先生の考えていたものとはかなりかけ離れた存在になる。

** 今回の章の詳細

主人公が今まで発見されていなかった遺跡へ調査に行かされる。横たわっているファンネルのスタンド使いの少年を見つける。この時にはスタンド使いだとはわかっていない。歳は10代半ばくらいに見える。同行している同僚がスタンド攻撃によって死亡する。同僚からスタンド能力を授けられる。少年を相手に戦闘、説得し、自分が所属している軍に連れて帰る。

** 登場人物の詳細

主人公は宇宙世紀側の人で、この章の中でスタンド能力を得る。能力は、死亡時に数瞬前に戻れる能力。死ぬたびに戻る時間幅は増えていく。戻る幅がものすごく増えて、自身が赤ん坊以上に戻ってしまった場合、自身の脳と五感が存在しなくなるため、自己の思考と外界の観測が不可能になる。このような能力を持っているために、伝説として語られていたニュータイプとして宇宙世紀の人々に持ち上げられるが、実際はスタンド能力であった、という話。
この章で新しく出てくるスタンド使いは、前々から考えていたもの。ファンネルを出すスタンド使い。ファンネルは自身の思考によって動かすことができ、射程は五十メートル。このファンネルはスタンドであるので、非スタンド使いには見えない。また、攻撃されると通常のスタンドと同じく本体にフィードバックがいく。

* 非日常到来
** 0

#+begin_quote
貴官を8番区異常出現区画調査任務に任命する。

-- 数時間前、ロジャー上官
#+end_quote

異常出現区画への調査か。…異常に出現する区画ってなんだ？
あの上官はいつも言葉が足りない。「勝手に風景が変わる場所」なんてあり得るわけがない。…はず。

先ほど手続きした軍用車両に乗り込む。軍で採用されている車だけあって、舗装された道路以外でも安定して走れるように口径が大きいタイヤが装着されている。入軍する前はテレビでしか見てなかったよなと思い返しながら、車のエンジンをかけた。

この寒い中にしばらく放置されていたエンジン。やっと仕事がやってきたと躍起になって動作する。この寒さだ、エンジンがかかるのにも時間が必要かと心配だったが、杞憂だったようだ。馬力が高い車だろうから、やはりかなりの騒音だ。

ふと窓の外を見ると、窓が曇り始めていたから見えづらかったが、かろうじて一人軍服を着た男性が走ってくるのが見えた。大方あいつだろう。既にシートベルトを装着していたものだったから、身を捩って反対側の助手席の扉を開けた。

「ゼェゼェ、流石に速すぎませんか、先輩！？」
「別に速すぎることはない。君が遅いだけだ」

何やら不平不満を吐き出していたようだったが、無視をした。任務はさっさと終わらせないとならない。彼が助手席に座り、扉を閉めたことを確認してから車を発進させた。

「ちょっと先輩、まだシートベルトしてないんですけど？」
「任務をちゃちゃっと終わらせて、こたつに入るためだ。お行儀が良いのは知っているが、我慢しろ」
「こたつは天国ですものねぇ。この寒い中…」
「なんだ、変ではなかろう」
「もちろんですよ」

軽く雑談を交わす。正直この後輩、少し苦手だ。なんだかまるで常にこちらのことを見透かしているかのような様子なのだ。私自身の話のテンポと、この後輩の話のテンポが絶妙に噛み合わない。できることならばあまり話したくないのだが、この後輩から私に近づいてくるのだから困る。

—— 現在地から車で約一時間の位置に、その区画、８番区異常出現区画はあるらしいですよ。少々遠い気がする…。って聞いてます！？

さっき乗車する前にもこの後輩が喚いていたのだが、その時に後輩の口から出た情報だった。この後輩と同じ感想を持つのはちょっと癪だが、確かに遠い気がする。この後輩は、軍隊にいるのだから当然なのかもしれないが、いつもの私へのとてもフレンドリーな態度と見比べてみると少し違和感を感じる程には嘘をつかない。まあ、元々は誠実な態度だったのだろう。一時間もかかるという情報は恐らく本当だ。

# この時点で、後輩は何万回も自分のスタンドによる死に戻りをしており、数十回前の死に戻りで本当なのだろうという先輩の口から出た言葉を聞いていた。そのために、今回もやっぱりそう思ったのだろうと予測して、愛おしくなり吹き出してしまった。
「ふふっ」
「なんだ急に笑って」
「何でもないですよ〜？」

その後も特筆すべきことは起きずに、運転は終了した。通ってきた道がオフロードであったためだろう、お尻が痛い。軍用車両というものにはあまり乗ったことがないのだが、クッションが硬いというのは噂通りだったようだ。強いて言うならば、例の場所に近づくにつれて後輩の元気が無くなっていったことか。まぁ大丈夫だろう、元気が無くとも冗談を言う余裕はあるようだし。

石造りの、言わば「古代の遺跡」が目の前に佇む。イメージとしてはアンコールワットが近いのだろうか、様子はまるで仏教の石造り建造物であった。その遺跡を見て私は思わず言葉を出した。

「デカいし、壮観だぁ…。すごいなぁ」
「…」
「どうした、いつもの調子じゃないな」
「いえ、大丈夫です」

何やら後輩が元気をなくしている。というか、まるで死地に行く軍人のように、顔は土気色になり、しかし覚悟を決めたような、そんな様子であった。もしかしてこの建造物のことを知っているのか…？
でもそんなことはないだろう。この遺跡を知ったタイミングは私と同じであった。現に、いつもの淡々とした形式の司令をいただいた時の、あの呆れたような顔は今も覚えている。そしてそれは、確かに覚悟を決めた雰囲気ではなかった。

不安が拭えない点がいくつかあれど、任務完了のためにも進まなければならない。私たちは遺跡内へと足を踏み出した。後輩は私の左後方から付いてきていた。なんか左後方にいられると気分的にむず痒くなる。

遺跡内部へと歩き出してしばらく経った。今の所遺跡内部には然程異変は無かった。後輩と二人でテクテクと歩いていると、風景も相まって後輩との観光にも思えてくる。

（そんな訳がない。ちゃんと目を凝らせ…。だってこの遺跡は人々が認識していない間に突如出現したんだぞ）

目で見ると普通の遺跡に見えるが、そんなはずはない。そんなはずはないのだ。建物が一瞬にして建造される訳がない。考えろ…。瞬時に現れた建物、転移してきた建物、当然インテリアも転移するだろう、同時に知的生命体も転移してくるかも…。

いやいや、さすがに知的生命体はないだろうと咄嗟に否定するも、建造物が一瞬で出現するならば、そのくらいは起こっても変ではないなと思い返す。

今何か不快なモヤッとしたのが頭を…。

その時、空気を切る音が左耳元で鳴った。数瞬反応が遅れたが、その飛来物らしきものは当たらなかった。私には。

左耳元で鳴ったものだから思わず左に振り向いた。今の音は何だ、と。その時の様子は、私の命が尽きて精神が朽ちるまでずっと忘れてはならないものだった。

その音源は、後輩の右目から脳天を、意図も容易くブチ抜いていった。残っていた左目は何かを伝えようとしているかのように、私の方を見ていた。

後輩の命が尽きていく。嗚呼あまり私から名前を呼んでいなかったよなぁと、どのように考えても今更である考えが浮かぶ。何故銃弾を撃たれている最中であるのに考えを巡らせられているのか、いくら理由を考えても、これは走馬灯なんだろうとしか分からなかった。

当たり前だが、音よりも人は速く動けない。敵は何処だと前方を向き、次に音が鳴った時には、眼球の目の前に飛来物があった。

** 1

（そんな訳がない。ちゃんと目を凝らせ…。だってこの遺跡は人々が認識していない間に突如出現したんだぞ）

目で見ると普通の遺跡に見えるが、そんなはずはない。そんなはずはないのだ。建物が一瞬にして建造される訳がない。考えろ…。瞬時に現れた建物、転移してきた建物、当然インテリアも転移するだろう、同時に知的生命体も転移してくるかも…。

いやいや、さすがに知的生命体はないだろうと咄嗟に否定するも、建造物が一瞬で出現するならば、そのくらいは起こっても変ではないなと思い返す。

今何か不快なモヤッとしたのが頭を…。…何か来るっ！！

明らかに五感以外の所から察知したモノを咄嗟に回避する。じゃあ何の感覚なんだと問われると分からないが、今の所はありがたく使わせてもらう。側道があってラッキーだと思いつつ、咄嗟の行動だったために、思わず見捨ててしまった後輩の方を流し見る。

後輩はあの時と同じ音源によって、左目から脳天にかけてブチ抜かれていた。…今思わずあの時と表現したが、デジャヴのようなものだろうか。具体的には思い出せずに、その記憶にはモヤが掛かっていた。

TODO…
